from pathlib import Path
import argparse
import json
import re

root = Path(__file__).resolve().parents[2]


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:80]


def classify(o):
    risks = " ".join(o.get("risk_flags", [])).lower()
    topic = o.get("topic", "").lower()
    seo = 4 if any(term in topic for term in ["workflow", "template", "guide"]) else 3
    geo = 5 if any(term in topic for term in ["workflow", "guide", "how to", "template"]) else 3
    risk = 1 if any(term in risks for term in ["legal", "medical", "financial", "high ymyl"]) else (3 if any(term in risks for term in ["thin", "affiliate bias"]) else 5)
    if risk <= 2:
        cls, rec = "Reject", "no-go: risk veto"
    elif seo >= 4 and geo >= 4:
        cls, rec = "Balanced SEO+GEO", "go: MVP pilot candidate"
    elif geo > seo:
        cls, rec = "GEO-led", "requires explicit human approval"
    else:
        cls, rec = "Defer", "defer until stronger evidence/fit"
    return {
        "opportunity_id": o["id"],
        "seo_score": seo,
        "geo_score": geo,
        "risk_fit_score": risk,
        "classification": cls,
        "recommendation": rec,
        "required_evidence_level": "medium" if risk >= 4 else "high",
        "human_review_triggers": [] if cls == "Balanced SEO+GEO" else ["risk/strategy review"],
    }


def pick_candidate(opportunities, strategy):
    by_id = {o["id"]: o for o in opportunities}
    balanced = [s for s in strategy if s["classification"] == "Balanced SEO+GEO"]
    if not balanced:
        return None
    balanced.sort(key=lambda s: (s["risk_fit_score"], s["geo_score"], s["seo_score"]), reverse=True)
    return by_id[balanced[0]["opportunity_id"]]


def make_evidence_plan(o):
    return {
        "opportunity_id": o["id"],
        "source_plan": o.get("source_candidates") or [
            "Official product/docs pages for factual capabilities",
            "Public standards or help-center pages when relevant",
            "Community questions as intent signals only",
            "Original examples/templates generated by the editorial workflow",
        ],
        "entity_map": o.get("entities") or ["target audience", "workflow", "tools", "source documents", "review step"],
        "claim_policy": "Separate factual claims from editorial guidance. Support product/tool capability claims with official sources before production publish.",
        "forbidden_claims": [
            "guaranteed outcomes",
            "unverified product capabilities",
            "medical/legal/financial advice unless explicitly reviewed by qualified experts",
            "copied competitor text or rankings",
        ],
        "evidence_requirements": [
            "concrete official URLs before Pass status",
            "dated review/update metadata",
            "clear distinction between source-backed facts and recommendations",
        ],
        "update_requirements": "Review quarterly or when source/tool capabilities materially change.",
        "human_review_triggers": ["privacy/security claims", "affiliate monetization", "missing official source URLs"],
    }


def make_placement(o):
    topic = o["topic"]
    cluster = o.get("recommended_cluster") or topic
    return {
        "opportunity_id": o["id"],
        "recommendation": "new_cluster_in_existing_site",
        "target_site": o.get("target_site", "productivity-ai-pilot"),
        "target_section": cluster,
        "target_page_type": "pillar_page",
        "fit_scores": {
            "audience_fit": 4,
            "topical_fit": 4,
            "entity_fit": 4,
            "intent_fit": 4,
            "internal_link_fit": 3,
            "trust_fit": 4,
            "risk_fit": 5,
            "monetization_fit": 4,
            "language_region_fit": 5,
            "scale_potential": 3,
        },
        "reasoning": {
            "summary": f"{topic} fits as a focused cluster/page inside the pilot site.",
            "why_not_new_site": "No separate audience, risk class, or entity posture has been established yet.",
            "why_not_existing_page_update": "No matching existing page was identified in this run.",
        },
        "human_review_required": False,
    }


def make_brief(o, evidence):
    title = o["topic"].strip().title()
    slug = slugify(o["topic"])
    cluster = o.get("recommended_cluster") or title
    direct = f"{title} should be built as an evidence-backed guide with a direct answer, step-by-step structure, source notes, and human review triggers before production publishing."
    return {
        "cluster_brief": {
            "cluster_name": cluster,
            "pillar_page": f"/{slug}/",
            "supporting_pages": [f"/{slug}-checklist/", f"/{slug}-examples/", f"/{slug}-faq/"],
            "internal_link_plan": ["homepage -> pillar", "pillar -> supporting pages", "supporting pages -> pillar"],
            "geo_structure_requirements": ["direct answer block", "definition box", "step-by-step workflow", "FAQ", "claim/evidence table"],
            "schema_plan": ["Article", "FAQPage", "BreadcrumbList"],
        },
        "page_brief": {
            "page_title": title,
            "slug": slug,
            "search_intent": o.get("search_intent", "informational"),
            "direct_answer_block": direct,
            "outline": ["Direct answer", "What this is", "Recommended workflow", "Evidence and source notes", "Review checklist", "FAQ"],
            "faq_questions": ["What problem does this solve?", "What evidence is needed before publishing?", "When should a human review it?"],
            "source_notes": evidence["source_plan"],
            "update_notes": [evidence["update_requirements"]],
        },
    }


def write_draft(brief, placement):
    page = brief["page_brief"]
    content_dir = root / "content" / "sites" / placement["target_site"] / "pages"
    content_dir.mkdir(parents=True, exist_ok=True)
    md = f'''---
title: "{page['page_title']}"
slug: "{page['slug']}"
site: "{placement['target_site']}"
status: "staging-draft"
geo_classification: "Balanced SEO+GEO"
last_reviewed: "2026-05-12"
---

# {page['page_title']}

## Direct answer

{page['direct_answer_block']}

## What this is

This staging draft is a structured SEO/GEO knowledge asset. It is designed to be easy for readers, search engines, and AI answer engines to parse, but it is not approved for production publishing yet.

## Recommended workflow

1. Confirm the reader intent and target audience.
2. Verify factual claims against official or primary sources.
3. Add examples, templates, or decision criteria that create original editorial value.
4. Separate source-backed facts from editorial recommendations.
5. Run QA for SEO, GEO readiness, evidence integrity, and scaled-content-abuse risk.
6. Keep the page in staging until the publish batch is approved.

## Evidence and source notes

The source plan must be converted into concrete URLs before this page can receive a Pass status.

## Review checklist

- Direct answer is present.
- Claims are either sourced or clearly marked as editorial guidance.
- No competitor text has been copied.
- Human review triggers are documented.

## FAQ

### What problem does this solve?

It turns an approved opportunity into a structured staging page that can be reviewed before publication.

### What evidence is needed before publishing?

Official source URLs, dated review metadata, and source-backed support for factual claims are required.

### When should a human review it?

A human should review it when source URLs are missing, privacy/security claims are present, or the topic changes risk class.
'''
    path = content_dir / f"{page['slug']}.md"
    path.write_text(md, encoding="utf-8")
    return path.relative_to(root)


def make_qa(draft_path):
    return {
        "page": str(draft_path),
        "status": "Needs Review",
        "checks": {
            "seo_quality": "Pass",
            "content_usefulness": "Pass",
            "evidence_source_integrity": "Needs Review: concrete official source URLs required",
            "geo_readiness": "Pass",
            "anti_spam_scaled_abuse": "Pass",
            "technical_publishing": "Pass",
        },
        "blockers": [],
        "required_before_publish": ["Replace source-plan placeholders with concrete official URLs", "Human review before production publish"],
    }


def main():
    parser = argparse.ArgumentParser(description="Run SEO/GEO factory stages for a run directory.")
    parser.add_argument("--run", required=True, help="Run directory, e.g. factory/runs/my-run")
    parser.add_argument("--stage", choices=["strategy", "full"], default="strategy")
    args = parser.parse_args()

    run_dir = Path(args.run)
    if not run_dir.is_absolute():
        run_dir = root / run_dir
    pool_path = run_dir / "inputs" / "opportunity_pool.json"
    if not pool_path.exists():
        raise SystemExit(f"Missing opportunity pool: {pool_path}")

    opportunities = json.loads(pool_path.read_text(encoding="utf-8"))
    strategy = [classify(o) for o in opportunities]
    (run_dir / "outputs").mkdir(exist_ok=True)
    (run_dir / "outputs" / "strategy_classification.json").write_text(json.dumps(strategy, indent=2), encoding="utf-8")

    if args.stage == "strategy":
        print(f"Classified {len(strategy)} opportunities for {run_dir.relative_to(root)}")
        return

    candidate = pick_candidate(opportunities, strategy)
    if candidate is None:
        raise SystemExit("No Balanced SEO+GEO candidate found; full pipeline stopped before content generation.")
    evidence = make_evidence_plan(candidate)
    placement = make_placement(candidate)
    brief = make_brief(candidate, evidence)
    draft_path = write_draft(brief, placement)
    qa = make_qa(draft_path)
    outputs = {
        "evidence_plan.json": evidence,
        "site_placement_decision.json": placement,
        "content_brief.json": brief,
        "qa_report.json": qa,
    }
    for name, payload in outputs.items():
        (run_dir / "outputs" / name).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Full pipeline generated candidate {candidate['id']} for {run_dir.relative_to(root)}")


if __name__ == "__main__":
    main()
