from pathlib import Path
import argparse
import json
import re

root = Path(__file__).resolve().parents[2]


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:80]


def classify(o):
    risks = " ".join(o.get("risk_flags", [])).lower()
    topic = o.get("topic", "").lower()
    seo = 4 if any(term in topic for term in ["workflow", "template", "guide"]) else 3
    geo = 5 if any(term in topic for term in ["workflow", "guide", "how to", "template"]) else 3
    high_risk = ["legal advice", "medical advice", "financial advice", "high ymyl"]
    risk = 1 if any(term in risks for term in high_risk) and "avoid financial advice" not in risks else (3 if any(term in risks for term in ["thin", "affiliate bias"]) else 5)
    if risk <= 2:
        cls, rec = "Reject", "no-go: risk veto"
    elif seo >= 4 and geo >= 4:
        cls, rec = "Balanced SEO+GEO", "go: MVP pilot candidate"
    elif geo > seo:
        cls, rec = "GEO-led", "requires explicit human approval"
    else:
        cls, rec = "Defer", "defer until stronger evidence/fit"
    return {
        "opportunity_id": o["id"],
        "seo_score": seo,
        "geo_score": geo,
        "risk_fit_score": risk,
        "classification": cls,
        "recommendation": rec,
        "required_evidence_level": "medium" if risk >= 4 else "high",
        "human_review_triggers": [] if cls == "Balanced SEO+GEO" else ["risk/strategy review"],
    }


def pick_candidates(opportunities, strategy, limit=None):
    by_id = {o["id"]: o for o in opportunities}
    balanced = [s for s in strategy if s["classification"] == "Balanced SEO+GEO"]
    balanced.sort(key=lambda s: (s["risk_fit_score"], s["geo_score"], s["seo_score"]), reverse=True)
    candidates = [by_id[s["opportunity_id"]] for s in balanced]
    return candidates[:limit] if limit else candidates


def make_evidence_plan(o):
    return {
        "opportunity_id": o["id"],
        "source_plan": o.get("source_candidates") or [
            "Official product/docs pages for factual capabilities",
            "Public standards or help-center pages when relevant",
            "Community questions as intent signals only",
            "Original examples/templates generated by the editorial workflow",
        ],
        "entity_map": o.get("entities") or ["target audience", "workflow", "tools", "source documents", "review step"],
        "claim_policy": "Separate factual claims from editorial guidance. Support product/tool capability claims with official sources before production publish.",
        "forbidden_claims": [
            "guaranteed outcomes",
            "unverified product capabilities",
            "medical/legal/financial advice unless explicitly reviewed by qualified experts",
            "copied competitor text or rankings",
        ],
        "evidence_requirements": [
            "concrete official URLs before Pass status",
            "dated review/update metadata",
            "clear distinction between source-backed facts and recommendations",
        ],
        "update_requirements": "Review quarterly or when source/tool capabilities materially change.",
        "human_review_triggers": ["privacy/security claims", "affiliate monetization", "missing official source URLs"],
    }


def infer_review_flags(o, evidence):
    risks = " ".join(o.get("risk_flags", [])).lower()
    source_items = evidence.get("source_plan", [])
    concrete_urls = [x for x in source_items if isinstance(x, str) and x.startswith(("http://", "https://"))]
    flags = {
        "missing_concrete_source_urls": len(concrete_urls) == 0,
        "privacy_review_required": "privacy" in risks or "customer" in risks or "crm" in " ".join(source_items).lower(),
        "copyright_review_required": "copyright" in risks or "copying" in risks or "content repurposing" in o.get("topic", "").lower(),
        "monetization_review_required": "affiliate" in risks or "sales" in o.get("topic", "").lower(),
        "high_risk_topic": any(term in risks for term in ["legal advice", "medical advice", "financial advice", "high ymyl"]) and "avoid financial advice" not in risks,
    }
    return flags


def make_source_verification(o, evidence):
    items = []
    for source in evidence.get("source_plan", []):
        is_url = isinstance(source, str) and source.startswith(("http://", "https://"))
        items.append({
            "source": source,
            "is_concrete_url": is_url,
            "verification_status": "not_checked" if is_url else "placeholder_requires_replacement",
            "required_before_pass": not is_url,
        })
    flags = infer_review_flags(o, evidence)
    return {
        "opportunity_id": o["id"],
        "source_items": items,
        "summary": {
            "total_sources": len(items),
            "concrete_urls": sum(1 for item in items if item["is_concrete_url"]),
            "placeholders": sum(1 for item in items if not item["is_concrete_url"]),
            "all_sources_publish_ready": bool(items) and all(item["is_concrete_url"] and item["verification_status"] == "checked" for item in items),
        },
        "review_flags": flags,
    }


def make_placement(o):
    topic = o["topic"]
    cluster = o.get("recommended_cluster") or topic
    return {
        "opportunity_id": o["id"],
        "recommendation": "new_cluster_in_existing_site",
        "target_site": o.get("target_site", "productivity-ai-pilot"),
        "target_section": cluster,
        "target_page_type": "pillar_page",
        "fit_scores": {
            "audience_fit": 4,
            "topical_fit": 4,
            "entity_fit": 4,
            "intent_fit": 4,
            "internal_link_fit": 3,
            "trust_fit": 4,
            "risk_fit": 5,
            "monetization_fit": 4,
            "language_region_fit": 5,
            "scale_potential": 3,
        },
        "reasoning": {
            "summary": f"{topic} fits as a focused cluster/page inside the pilot site.",
            "why_not_new_site": "No separate audience, risk class, or entity posture has been established yet.",
            "why_not_existing_page_update": "No matching existing page was identified in this run.",
        },
        "human_review_required": False,
    }


def make_brief(o, evidence):
    title = o["topic"].strip().title()
    slug = slugify(o["topic"])
    cluster = o.get("recommended_cluster") or title
    direct = f"{title} should be built as an evidence-backed guide with a direct answer, step-by-step structure, source notes, and human review triggers before production publishing."
    return {
        "cluster_brief": {
            "cluster_name": cluster,
            "pillar_page": f"/{slug}/",
            "supporting_pages": [f"/{slug}-checklist/", f"/{slug}-examples/", f"/{slug}-faq/"],
            "internal_link_plan": ["homepage -> pillar", "pillar -> supporting pages", "supporting pages -> pillar"],
            "geo_structure_requirements": ["direct answer block", "definition box", "step-by-step workflow", "FAQ", "claim/evidence table"],
            "schema_plan": ["Article", "FAQPage", "BreadcrumbList"],
        },
        "page_brief": {
            "page_title": title,
            "slug": slug,
            "search_intent": o.get("search_intent", "informational"),
            "direct_answer_block": direct,
            "outline": ["Direct answer", "What this is", "Recommended workflow", "Evidence and source notes", "Review checklist", "FAQ"],
            "faq_questions": ["What problem does this solve?", "What evidence is needed before publishing?", "When should a human review it?"],
            "source_notes": evidence["source_plan"],
            "update_notes": [evidence["update_requirements"]],
        },
    }


def write_draft(brief, placement):
    page = brief["page_brief"]
    content_dir = root / "content" / "sites" / placement["target_site"] / "pages"
    content_dir.mkdir(parents=True, exist_ok=True)
    md = f'''---
title: "{page['page_title']}"
slug: "{page['slug']}"
site: "{placement['target_site']}"
status: "staging-draft"
geo_classification: "Balanced SEO+GEO"
last_reviewed: "2026-05-12"
---

# {page['page_title']}

## Direct answer

{page['direct_answer_block']}

## What this is

This staging draft is a structured SEO/GEO knowledge asset. It is designed to be easy for readers, search engines, and AI answer engines to parse, but it is not approved for production publishing yet.

## Recommended workflow

1. Confirm the reader intent and target audience.
2. Verify factual claims against official or primary sources.
3. Add examples, templates, or decision criteria that create original editorial value.
4. Separate source-backed facts from editorial recommendations.
5. Run QA for SEO, GEO readiness, evidence integrity, and scaled-content-abuse risk.
6. Keep the page in staging until the publish batch is approved.

## Evidence and source notes

The source plan must be converted into concrete URLs before this page can receive a Pass status.

## Review checklist

- Direct answer is present.
- Claims are either sourced or clearly marked as editorial guidance.
- No competitor text has been copied.
- Human review triggers are documented.

## FAQ

### What problem does this solve?

It turns an approved opportunity into a structured staging page that can be reviewed before publication.

### What evidence is needed before publishing?

Official source URLs, dated review metadata, and source-backed support for factual claims are required.

### When should a human review it?

A human should review it when source URLs are missing, privacy/security claims are present, or the topic changes risk class.
'''
    path = content_dir / f"{page['slug']}.md"
    path.write_text(md, encoding="utf-8")
    return path.relative_to(root)


def make_qa(draft_path, source_verification):
    flags = source_verification["review_flags"]
    blockers = []
    required = ["Human review before production publish"]
    if flags["missing_concrete_source_urls"]:
        required.append("Replace source-plan placeholders with concrete official URLs")
    if flags["privacy_review_required"]:
        required.append("Privacy/data-handling review")
    if flags["copyright_review_required"]:
        required.append("Copyright/IP review")
    if flags["monetization_review_required"]:
        required.append("Monetization/disclosure review")
    if flags["high_risk_topic"]:
        blockers.append("High-risk topic requires explicit approval or rejection")
    status = "Block" if blockers else "Needs Review"
    return {
        "page": str(draft_path),
        "status": status,
        "checks": {
            "seo_quality": "Pass",
            "content_usefulness": "Pass",
            "evidence_source_integrity": "Needs Review: concrete official source URLs required" if flags["missing_concrete_source_urls"] else "Needs Review: source URLs need verification",
            "geo_readiness": "Pass",
            "anti_spam_scaled_abuse": "Pass",
            "technical_publishing": "Pass",
        },
        "review_flags": flags,
        "blockers": blockers,
        "required_before_publish": required,
    }


def main():
    parser = argparse.ArgumentParser(description="Run SEO/GEO factory stages for a run directory.")
    parser.add_argument("--run", required=True, help="Run directory, e.g. factory/runs/my-run")
    parser.add_argument("--stage", choices=["strategy", "full"], default="strategy")
    parser.add_argument("--limit", type=int, help="Maximum candidates to generate in full stage. Defaults to all Balanced SEO+GEO candidates.")
    args = parser.parse_args()

    run_dir = Path(args.run)
    if not run_dir.is_absolute():
        run_dir = root / run_dir
    pool_path = run_dir / "inputs" / "opportunity_pool.json"
    if not pool_path.exists():
        raise SystemExit(f"Missing opportunity pool: {pool_path}")

    opportunities = json.loads(pool_path.read_text(encoding="utf-8"))
    strategy = [classify(o) for o in opportunities]
    (run_dir / "outputs").mkdir(exist_ok=True)
    (run_dir / "outputs" / "strategy_classification.json").write_text(json.dumps(strategy, indent=2), encoding="utf-8")

    if args.stage == "strategy":
        print(f"Classified {len(strategy)} opportunities for {run_dir.relative_to(root)}")
        return

    candidates = pick_candidates(opportunities, strategy, args.limit)
    if not candidates:
        raise SystemExit("No Balanced SEO+GEO candidate found; full pipeline stopped before content generation.")

    page_records = []
    for candidate in candidates:
        evidence = make_evidence_plan(candidate)
        source_verification = make_source_verification(candidate, evidence)
        placement = make_placement(candidate)
        brief = make_brief(candidate, evidence)
        draft_path = write_draft(brief, placement)
        qa = make_qa(draft_path, source_verification)
        page_dir = run_dir / "outputs" / "pages" / candidate["id"]
        page_dir.mkdir(parents=True, exist_ok=True)
        per_page = {
            "evidence_plan.json": evidence,
            "source_verification.json": source_verification,
            "site_placement_decision.json": placement,
            "content_brief.json": brief,
            "qa_report.json": qa,
        }
        for name, payload in per_page.items():
            (page_dir / name).write_text(json.dumps(payload, indent=2), encoding="utf-8")
        page_records.append({
            "opportunity_id": candidate["id"],
            "topic": candidate["topic"],
            "draft_path": str(draft_path),
            "slug": brief["page_brief"]["slug"],
            "qa_status": qa["status"],
            "review_flags": qa["review_flags"],
            "blockers": qa["blockers"],
            "required_before_publish": qa["required_before_publish"],
        })

    first = candidates[0]
    first_dir = run_dir / "outputs" / "pages" / first["id"]
    # Keep legacy top-level outputs pointing at the first generated candidate for simple validators/CI.
    for name in ["evidence_plan.json", "source_verification.json", "site_placement_decision.json", "content_brief.json", "qa_report.json"]:
        (run_dir / "outputs" / name).write_text((first_dir / name).read_text(encoding="utf-8"), encoding="utf-8")

    flag_counts = {}
    for record in page_records:
        for flag, value in record["review_flags"].items():
            if value:
                flag_counts[flag] = flag_counts.get(flag, 0) + 1
    status_counts = {}
    for record in page_records:
        status_counts[record["qa_status"]] = status_counts.get(record["qa_status"], 0) + 1
    batch_qa_summary = {
        "status_counts": status_counts,
        "review_flag_counts": flag_counts,
        "publish_readiness": "Block" if status_counts.get("Block") else "Needs Review",
    }
    batch = {
        "run": str(run_dir.relative_to(root)),
        "status": batch_qa_summary["publish_readiness"],
        "generated_pages": page_records,
        "batch_qa_summary": batch_qa_summary,
        "publish_allowed": False,
        "reason": "Staging drafts require concrete source URLs and human review before publish approval.",
    }
    (run_dir / "outputs" / "batch_publish_report.json").write_text(json.dumps(batch, indent=2), encoding="utf-8")
    md_lines = ["# Batch Publish Report", "", f"Status: {batch_qa_summary['publish_readiness']}", "", "## Batch QA Summary", "", f"Status counts: `{status_counts}`", "", f"Review flag counts: `{flag_counts}`", "", "| Page | QA | Flags | Draft | Required before publish |", "|---|---|---|---|---|"]
    for r in page_records:
        active_flags = ", ".join([k for k, v in r['review_flags'].items() if v]) or "none"
        md_lines.append(f"| {r['topic']} | {r['qa_status']} | {active_flags} | `{r['draft_path']}` | {'; '.join(r['required_before_publish'])} |")
    md_lines.append("\nPublishing is not allowed until the batch is approved by a human reviewer.")
    (run_dir / "outputs" / "batch_publish_report.md").write_text("\n".join(md_lines), encoding="utf-8")
    print(f"Full pipeline generated {len(candidates)} candidate(s) for {run_dir.relative_to(root)}")


if __name__ == "__main__":
    main()
